# permissions for end users to view dgraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dgraph-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-operator-dgraph
    app.kubernetes.io/part-of: kubernetes-operator-dgraph
    app.kubernetes.io/managed-by: kustomize
  name: dgraph-viewer-role
rules:
- apiGroups:
  - roshanbhatia.com
  resources:
  - dgraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - roshanbhatia.com
  resources:
  - dgraphs/status
  verbs:
  - get
